--- #YAML:1.0
name:               Net-Traceroute-PurePerl
version:            0.10_01
abstract:           traceroute(1) implementation in Perl using raw sockets
author:
    - Tom Scanlan <tscanlan@openreach.com>, Andrew Hoying <ahoying@cpan.org>, John Kristoff <jtk@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Net::Traceroute:  1.05
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
